CREATE TABLE IF NOT EXISTS company (
    id INT GENERATED BY DEFAULT AS IDENTITY ,
    company_name VARCHAR (255) UNIQUE NOT NULL ,
    email VARCHAR (255) UNIQUE NOT NULL ,
    password VARCHAR (255) NOT NULL ,
    company_phone VARCHAR (255) UNIQUE NOT NULL ,
    about_us VARCHAR (255) NOT NULL ,
    company_status VARCHAR (255) NOT NULL ,
    PRIMARY KEY (id));

