CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY ,
    email VARCHAR (255) UNIQUE NOT NULL ,
    password VARCHAR (255) NOT NULL ,
    first_name VARCHAR (255) NOT NULL ,
    last_name VARCHAR (255) NOT NULL ,
    user_phone VARCHAR (255) UNIQUE NOT NULL ,
    user_roles VARCHAR (255) NOT NULL ,
    user_status VARCHAR (255) NOT NULL ,
    PRIMARY KEY (id));

INSERT INTO users(email,password,first_name,last_name,user_phone,user_roles,user_status)
VALUES (
           'admin@mail.ru',
           '$2a$12$oodcy9aUT0ei287ipTSjI.N9lmcndCuXpoQh4G9lsy.H.i17cP3B.',
           'Admin',
           'Adminov',
           '1234567',
           'ADMIN',
           'ACTIVE'
       );