CREATE TABLE IF NOT EXISTS vacancy (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    vacancy_name VARCHAR (255) NOT NULL ,
    requirements VARCHAR (255) NOT NULL,
    abilities VARCHAR (255) NOT NULL,
    proposition VARCHAR (255) NOT NULL,

    PRIMARY KEY (id));
